version: 2.1
# Define a common Docker container and environment for jobs
executors:
  docker-publisher:
    # Define the image tag
    environment:
      IMAGE_TAG: k0w4sk1/agendacloud:latest
      PLATFORMS: linux/amd64,linux/arm64
    docker:
      - image: cimg/base:stable

jobs:
  build:
    executor: docker-publisher
    steps:
      # Checkout the repository files (Download files from git)
      - checkout
      # Set up a separate Docker environment to run `docker` commands in
      - setup_remote_docker:
          version: 20.10.12
      # install dependencies
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt install -y nodejs
            cd app
            sudo npm install --global gulp-cli
            npm install
            gulp build
      # prepare docker buildx
      - run:
          name: Prepare docker buildx
          command: |
            docker buildx install
            docker version
            docker buildx version
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker context create xbuilder
            docker buildx create xbuilder --name xbuilder --use
            docker buildx inspect --bootstrap
      # build and push docker image
      - run:
          name: Build Docker image
          command: |
            cd app/build
            docker buildx build --platform ${PLATFORMS} --tag "${IMAGE_TAG}" --push .
workflows:
  version: 2
  build-push:
    jobs:
      - build:
          filters:
            branches:
              only: main