version: 2.1
# Define a common Docker container and environment for jobs
executors:
  docker-publisher:
    # Define the image tag
    environment:
      IMAGE_TAG: k0w4sk1/agendacloud:latest
    docker:
      - image: cimg/base:stable

jobs:
  build:
    executor: docker-publisher
    steps:
      # Checkout the repository files (Download files from git)
      - checkout
      # Set up a separate Docker environment to run `docker` commands in
      - setup_remote_docker:
          version: 20.10.12
      # install dependencies
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt install -y nodejs
            cd app
            npm install --global gulp-cli
            npm install
            gulp build
      # build docker image
      - run:
          name: Build Docker image
          command: |
            cd app/build
            docker build --tag "${IMAGE_TAG}" .
      - run:
          name: Archive Docker image
          command: docker save --output image.tar "${IMAGE_TAG}"
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  push:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker image
          command: docker load --input /tmp/workspace/image.tar
      - run:
          name: Publish Docker image
          command: |
            echo "${DOCKERHUB_PASS}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
            docker push "${IMAGE_TAG}"

workflows:
  version: 2
  build-push:
    jobs:
      - build
      - push:
          requires:
            - build
          filters:
            branches:
              only: main